default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgrespwd
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: invue_development

test:
  <<: *default
  database: invue_test

production:
  url: <%= ENV['INVUE_DATABASE_URL'] %>
