apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: invue
          image: docker.io/michelsazevedo/invue
          command: ['rails']
          args: ['db:migrate']
          env:
            - name: RAILS_ENV
              value: production
            - name: PORT
              value: '80'
            - name: INVUE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: invue-secrets
                  key: database-url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: invue-secrets
                  key: secret-key-base

